var mongoose = require('mongoose');
var Schema   = mongoose.Schema;

var postSchema = new Schema({
  domain: String,
  banned_by: String,
  media_embed: mongoose.Schema.Types.Mixed,
  subreddit: String,
  selftext_html: String,
  selftext: String,
  likes: Number,
  user_reports: [String],
  secure_media: String,
  link_flair_text: String,
  id: String,
  gilded: Number,
  secure_media_embed: mongoose.Schema.Types.Mixed,
  clicked: Boolean,
  report_reasons: mongoose.Schema.Types.Mixed,
  author: String,
  media: String,
  score: Number,
  approved_by: String,
  over_18: Boolean,
  hidden: Boolean,
  thumbnail: String,
  subreddit_id: String,
  edited: Boolean,
  link_flair_css_class: String,
  author_flair_css_class: String,
  downs: Number,
  mod_reports: [String],
  saved: Boolean,
  is_self: Boolean,
  name: String,
  permalink: String,
  stickied: Boolean,
  created: Number,
  url: String,
  author_flair_text: String,
  title: String,
  created_utc: Number,
  ups: Number,
  num_comments: Number,
  visited: Boolean,
  num_reports: Number,
  distinguished: mongoose.Schema.Types.Mixed
});

var artworkSchema = new Schema({
  post_id: mongoose.Schema.Types.ObjectId,
  subreddit_id: String,
  banned_by: String,
  link_id: String,
  likes: Number,
  replies: [String],
  user_reports: [String],
  saved: Boolean,
  url: String,
  id: String,
  gilded: Number,
  report_reasons: mongoose.Schema.Types.Mixed,
  author: String,
  parent_id: String,
  score: Number,
  approved_by: mongoose.Schema.Types.Mixed,
  controversiality: Number,
  body: String,
  edited: Number,
  author_flair_css_class: String,
  downs: Number,
  body_html: String,
  subreddit: String,
  score_hidden: Boolean,
  name: String,
  created: Number,
  author_flair_text: String,
  created_utc: Number,
  distinguished: mongoose.Schema.Types.Mixed,
  mod_reports: [String],
  num_reports: Number,
  ups: Number
});

mongoose.model('Post', postSchema);
mongoose.model('Artwork', artworkSchema);

mongoose.connect('mongodb://localhost/gotdrawn');